trigger:
  branches:
    include:
      - CI_testing
  tags:
    exclude:
      - '*'
pr:
  branches:
    include:
      - master
jobs:

- job: Windows_Build
  variables:
    COMPILER: msvc
    QT_VER: '5.14.1'
    QT_DATE: '202001240957'
    QTDIR: C:\Qt\$(QT_VER)\msvc2017_64
    VULKAN_VER: '1.2.135.0'
    VULKAN_SDK_SHA: '181b3353612c8b0fc5e1857b652d62140191ae42b98f2f0d532cf349cebfd8c6'
    VULKAN_SDK: C:\VulkanSDK\$(VULKAN_VER)
    CACHE_DIR: ./cache
    CCACHE_DIR: ./ccache

  pool:
    vmImage: "windows-latest"

  steps:
    - task: Cache@2
      inputs:
        key: $(Agent.OS) | $(COMPILER)
        path: $(CACHE_DIR)
      displayName: Cache
    
    - task: Cache@2
      inputs:
        key: ccache | $(Agent.OS) | $(COMPILER)
        path: $(CCACHE_DIR)
      displayName: ccache

    - bash: .ci/setup-windows.sh
      displayName: Download and unpack dependencies

    - bash: .ci/export-azure-vars.sh
      displayName: Export Variables

    - task: MSBuild@1
      inputs:
        solution: './Vulkan/spirv-tools-build/spirv-tools-build.vcxproj'
        maximumCpuCount: true
        platform: x64
        configuration: 'Release'
      displayName: Compile SPIRV-Tools

    - task: VSBuild@1
      inputs:
        solution: 'rpcs3.sln'
        maximumCpuCount: true
        platform: x64
        configuration: 'Release - LLVM'
      displayName: Compile RPCS3

    - bash: .ci/cache-windows.sh
      displayName: Write Cache

    - bash: .ci/deploy-windows.sh
      displayName: Pack up build artifacts

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: Windows App Bundle
